#!/bin/bash

if [ -n "$1" ]
then
T=$1
else
T=20
fi



echo " ### plotting position x y z [m] ###"
echo " ### plotting velocities x y z [m/s] ###"
echo " ### plotting acceleration bias x y z [m/s^2] ###"
echo " ### plotting scale ###"
echo " ### buffer = " $T "sec"

rxplot sensor_fusion/state_out/data[0]:data[1]:data[2] sensor_fusion/state_out/data[3]:data[4]:data[5] sensor_fusion/state_out/data[16] -b $T -t "position / velocity / scale" -l px,py,pz,vx,vy,vz,L &
rxplot sensor_fusion/state_out/data[6]:data[7]:data[8]:data[9] sensor_fusion/state_out/data[32]:data[33]:data[34] -b $T -t "attitude / p_ig" -l w,x,y,z,px,py,pz &

rxplot sensor_fusion/state_out/data[13]:data[14]:data[15] sensor_fusion/state_out/data[10]:data[11]:data[12] -b $T -t "acc bias / gyr bias" -l ax,ay,az,wx,wy,wz &

rxplot sensor_fusion/state_out/data[17]:data[18]:data[19]:data[20] sensor_fusion/state_out/data[35]:data[36]:data[37] -b $T -t "q_vw / p_vw" -l w,x,y,z,px,py,pz &
rxplot sensor_fusion/state_out/data[28]:data[29]:data[30]:data[31] sensor_fusion/state_out/data[38]:data[39] -b $T -t "q_im / alpha / beta" -l w,x,y,z,alpha,beta &

rxplot sensor_fusion/state_out/data[21]:data[22]:data[23]:data[24]  sensor_fusion/state_out/data[25]:data[26]:data[27] -b $T -t "q_ic / p_ic" -l w,x,y,z,px,py,pz &


