#!/bin/bash

if [ -n "$1" ]
then
T=$1
else
T=5
fi

echo " ### plotting gyro bias x y z [rad/s] ###"
echo " ### buffer = " $T "sec"

rxplot msf_core/state_out/data[10]:data[11]:data[12] -b $T -t "gyr bias" -l x,y,z 
