#!/bin/bash

if [ -n "$1" ]
then
T=$1
else
T=20
fi

echo " ### plotting vision-world drift qw qx qy qz [quat] ###"
echo " ### buffer = " $T "sec"

rxplot ssf_core/state_out/data[17]:data[18]:data[19]:data[20] -b $T -t "q_vw" -l w,x,y,z 
