#!/bin/bash

if [ -n "$1" ]
then
T=$1
else
T=5
fi

T=55

echo " ### plotting position x y z [m] ###"
echo " ### buffer = " $T "sec"

rosrun rxtools rxplot /ref/msf_core/state_out/data[0]:data[1]:data[2] /msf_distort/tf_to_pose_output/pose/position/x:y:z -b $T -t "position / gt" -l x,y,z,gt_x,gt_y,gt_z -p 55

