#!/bin/bash

if [ -n "$1" ]
then
T=$1
else
T=20
fi

echo " ### plotting attitude qw qx qy qz [quat] ###"
echo " ### buffer = " $T "sec"

rxplot ssf_core/state_out/data[6]:data[7]:data[8]:data[9] -b $T -t "attitude" -l w,x,y,z 
