#!/bin/bash

if [ -n "$1" ]
then
T=$1
else
T=20
fi

echo " ### plotting position x y z [m] ###"
echo " ### plotting velocities x y z [m/s] ###"
echo " ### plotting acceleration bias x y z [m/s^2] ###"
echo " ### plotting scale ###"
echo " ### buffer = " $T "sec"

rxplot ssf_core/state_out/data[0]:data[1]:data[2] ssf_core/state_out/data[3]:data[4]:data[5] -b $T -t "position & velocity" -l px,py,pz,vx,vy,vz &
rxplot ssf_core/state_out/data[13]:data[14]:data[15] ssf_core/state_out/data[16] -b $T -t "acc bias & scale" -l x,y,z,L 


