#!/bin/bash

if [ -n "$1" ]
then
T=$1
else
T=5
fi

T=55

echo " ### plotting attitude qw qx qy qz [quat] ###"
echo " ### buffer = " $T "sec"

rosrun rxtools rxplot /msf_core/state_out/data[6]:data[7]:data[8]:data[9] -b $T -t "attitude" -l w,x,y,z -p 55

