#!/bin/bash

if [ -n "$1" ]
then
T=$1
else
T=5
fi

echo " ### plotting vision-world drift px py pz [vector3] ###"
echo " ### buffer = " $T "sec"

rxplot msf_core/state_out/data[28]:data[29]:data[30] -b $T -t "p_vw" -l x,y,z 
