#!/bin/bash

if [ -n "$1" ]
then
T=$1
else
T=5
fi

echo " ### plotting attitude q_ii w x y z [quat] ###"
echo " ### plotting translation p_ic x y z [m] ###"
echo " ### buffer = " $T "sec"

rxplot msf_core/state_out/data[24]:data[25]:data[26]:data[27]  msf_core/state_out/data[28]:data[29]:data[30] -b $T -t "attitude q_ic & translation p_ic" -l qw,qx,qy,qz,tx,ty,tz 


