#!/bin/bash

if [ -n "$1" ]
then
T=$1
else
T=20
fi

echo " ### plotting acceleration bias x y z [m/s^2] ###"
echo " ### buffer = " $T "sec"

rxplot ssf_core/state_out/data[13]:data[14]:data[15] -b $T -t "acc bias" -l x,y,z
